# Generated by Django 5.1.5 on 2025-02-03 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(blank=True, max_length=128, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoperfil', models.ImageField(blank=True, null=True, upload_to='perfilUsuarioimagen/')),
                ('activo', models.BooleanField(default=1)),
                ('instituto', models.CharField(blank=True, max_length=128, null=True)),
                ('pais', models.CharField(blank=True, max_length=128, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idactividad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.BigIntegerField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fechaentrega', models.DateField()),
                ('fechacreacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('estado', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Actividadcronograma',
            fields=[
                ('titulo', models.CharField(max_length=20)),
                ('fechacreacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('fechainicial', models.DateField(blank=True, null=True)),
                ('fechafinal', models.DateField(blank=True, null=True)),
                ('idactividad', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'actividadCronograma',
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('idcomponente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Componente',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('lugar', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('director', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.SmallIntegerField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('idproyecto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.SmallIntegerField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
                ('personalequiposcriticos', models.TextField(blank=True, null=True)),
                ('razon', models.TextField(blank=True, null=True)),
                ('requerimientominimos', models.TextField(blank=True, null=True)),
                ('imagen', models.TextField(blank=True, null=True)),
                ('areasinvestigacion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Desafio',
            },
        ),
        migrations.CreateModel(
            name='ArchivoActividades',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.TextField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
                ('idarchivo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idactividad', models.ForeignKey(blank=True, db_column='idactividad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.actividad')),
            ],
            options={
                'db_table': 'Archivo_actividades',
            },
        ),
        migrations.CreateModel(
            name='Actividadtecnica',
            fields=[
                ('idactividadtecnica', models.BigIntegerField(db_column='idactividadTecnica', primary_key=True, serialize=False)),
                ('tipo', models.BigIntegerField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechainicio', models.DateField(blank=True, null=True)),
                ('fechafinal', models.DateField(blank=True, null=True)),
                ('activo', models.DateField()),
                ('fechacreacion', models.DateField()),
                ('titulo', models.CharField(max_length=20)),
                ('idcomponente', models.ForeignKey(db_column='idcomponente', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.componente')),
            ],
            options={
                'db_table': 'actividadTecnica',
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('idconvocatoria', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fechacreacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('estado', models.SmallIntegerField()),
                ('objetivogeneral', models.TextField(blank=True, null=True)),
                ('prioridadesconvocatoria', models.TextField(blank=True, null=True)),
                ('publicoobjetivo', models.TextField(blank=True, null=True)),
                ('imagen', models.BigIntegerField(blank=True, null=True)),
                ('idactividad', models.ForeignKey(blank=True, db_column='idactividad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.actividadcronograma')),
            ],
            options={
                'db_table': 'Convocatoria',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idcurso', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('nivel', models.CharField(blank=True, max_length=20, null=True)),
                ('anioacademico', models.IntegerField()),
                ('semestre', models.SmallIntegerField(blank=True, null=True)),
                ('coordinador', models.CharField(blank=True, max_length=20, null=True)),
                ('fecharegistro', models.DateField()),
                ('estado', models.SmallIntegerField()),
                ('activo', models.BooleanField()),
                ('iddepartamento', models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.departamento')),
            ],
            options={
                'db_table': 'Curso',
            },
        ),
        migrations.CreateModel(
            name='PostulacionPropuesta',
            fields=[
                ('idproyecto', models.OneToOneField(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='gestioninvestigacionapp.desafio')),
                ('detallepropuesta', models.TextField()),
                ('titulo', models.TextField()),
                ('practico', models.FloatField(blank=True, null=True)),
                ('rentable', models.FloatField(blank=True, null=True)),
                ('pionero', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('practicocomentario', models.TextField(blank=True, null=True)),
                ('rentrablecomentario', models.TextField(blank=True, null=True)),
                ('pionerocomentario', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField()),
                ('cumplimientorequerimientos', models.TextField()),
            ],
            options={
                'db_table': 'postulacion_propuesta',
            },
        ),
        migrations.AddField(
            model_name='desafio',
            name='idconvocatoria',
            field=models.ForeignKey(blank=True, db_column='idconvocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.convocatoria'),
        ),
        migrations.AddField(
            model_name='desafio',
            name='idcurso',
            field=models.ForeignKey(blank=True, db_column='idcurso', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.curso'),
        ),
        migrations.AddField(
            model_name='componente',
            name='idproyecto',
            field=models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio'),
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.TextField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
                ('idarchivo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idconvocatoria', models.ForeignKey(blank=True, db_column='idconvocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.convocatoria')),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'Archivo',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='idproyecto',
            field=models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio'),
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('identregable', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pdfentregable', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('idactividadtecnica', models.ForeignKey(blank=True, db_column='idactividadTecnica', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.actividadtecnica')),
            ],
            options={
                'db_table': 'Entregable',
            },
        ),
        migrations.CreateModel(
            name='Notificciones',
            fields=[
                ('idnotificacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
                ('iduser', models.ForeignKey(blank=True, db_column='iduser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Notificciones',
            },
        ),
        migrations.CreateModel(
            name='Plantesis',
            fields=[
                ('idplanformacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=20, null=True)),
                ('justificacion', models.CharField(blank=True, max_length=20, null=True)),
                ('abstract', models.CharField(max_length=20)),
                ('objgeneral', models.TextField(blank=True, null=True)),
                ('objetivosespecificos', models.TextField(blank=True, null=True)),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'PlanTesis',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('idevaluacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('pionero', models.FloatField()),
                ('rentable', models.FloatField()),
                ('practico', models.FloatField()),
                ('total', models.FloatField()),
                ('idplanformacion', models.ForeignKey(blank=True, db_column='idplanformacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.plantesis')),
            ],
            options={
                'db_table': 'Evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('partida', models.CharField(max_length=20)),
                ('monto', models.FloatField()),
                ('idpresupuesto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'Presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('idreporte', models.BigIntegerField(primary_key=True, serialize=False)),
                ('evaluacionnota', models.BigIntegerField(blank=True, null=True)),
                ('pdf', models.BigIntegerField(blank=True, null=True)),
                ('idactividad', models.ForeignKey(blank=True, db_column='idactividad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.actividad')),
            ],
            options={
                'db_table': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacion',
            fields=[
                ('idretroalimentacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('idreporte', models.ForeignKey(blank=True, db_column='idreporte', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.reporte')),
            ],
            options={
                'db_table': 'Retroalimentacion',
            },
        ),
        migrations.CreateModel(
            name='Retroalimentacionacttecnica',
            fields=[
                ('idretroalimentacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('identregable', models.ForeignKey(blank=True, db_column='identregable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.entregable')),
            ],
            options={
                'db_table': 'Retroalimentacionacttecnica',
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('idrubrica', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'Rubrica',
            },
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('iduser', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('institucion', models.CharField(blank=True, max_length=20, null=True)),
                ('fechacreacion', models.DateField()),
                ('activo', models.BooleanField()),
                ('pais', models.CharField(blank=True, max_length=20, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=20, null=True)),
                ('fotoperfil', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.postulacionpropuesta')),
            ],
            options={
                'db_table': 'Postulante',
            },
        ),
        migrations.CreateModel(
            name='ArchivoPostulaciones',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.TextField()),
                ('activo', models.BooleanField()),
                ('fechacreacion', models.DateField()),
                ('idarchivo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idconvocatoria', models.BigIntegerField(blank=True, null=True)),
                ('idproyecto', models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.postulacionpropuesta')),
            ],
            options={
                'db_table': 'Archivo_postulaciones',
            },
        ),
        migrations.CreateModel(
            name='UserCurso',
            fields=[
                ('iduser', models.OneToOneField(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.SmallIntegerField()),
                ('idcurso', models.ForeignKey(db_column='idcurso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.curso')),
            ],
            options={
                'db_table': 'user_curso',
                'unique_together': {('iduser', 'idcurso')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioDesafio',
            fields=[
                ('iduser', models.OneToOneField(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.SmallIntegerField()),
                ('idproyecto', models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'usuario_desafio',
                'unique_together': {('iduser', 'idproyecto')},
            },
        ),
    ]
