# Generated by Django 5.1.5 on 2025-04-29 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retroalimentacion',
            name='idreporte',
        ),
        migrations.AddField(
            model_name='actividad',
            name='idcreador',
            field=models.ForeignKey(db_column='iduser', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='idactividad',
            field=models.ForeignKey(db_column='idactividad', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.actividad'),
            preserve_default=False,
        ),
    ]
