# Generated by Django 5.1.5 on 2025-04-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idhistoriaexito', models.BigAutoField(db_column='idhistoriaexito', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='desafioimagen/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('publico', models.IntegerField()),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Historiaexito',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idhistoriaexito', models.BigAutoField(db_column='idhistoriaexito', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='desafioimagen/')),
                ('historia', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'HistoriaExito',
            },
        ),
        migrations.AlterField(
            model_name='actividadtecnica',
            name='idactividadtecnica',
            field=models.BigAutoField(db_column='idactividadTecnica', primary_key=True, serialize=False),
        ),
    ]
