# Generated by Django 5.1.5 on 2025-02-25 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0002_convocatoria_fechaevaluacion_departamento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='desafio',
            name='idconvocatoria',
            field=models.ForeignKey(blank=True, db_column='idconvocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.convocatoria'),
        ),
    ]
