# Generated by Django 5.1.5 on 2025-04-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0002_empresa_historiaexito_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='idhistoriaexito',
        ),
        migrations.AddField(
            model_name='empresa',
            name='idempresa',
            field=models.BigAutoField(db_column='idempresa', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresaimagen/'),
        ),
        migrations.AlterField(
            model_name='historiaexito',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='historiaexitoimagen/'),
        ),
    ]
