# Generated by Django 5.1.5 on 2025-04-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0002_remove_retroalimentacion_idreporte_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleCompleto',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='idrubrica',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='idcurso',
            field=models.ForeignKey(db_column='idcurso', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.curso'),
            preserve_default=False,
        ),
    ]
