# Generated by Django 5.1.5 on 2025-05-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0003_delete_detallecompleto_remove_curso_idrubrica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaentrega',
            field=models.DateTimeField(),
        ),
    ]
