# Generated by Django 5.1.5 on 2025-04-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0003_remove_empresa_idhistoriaexito_empresa_idempresa_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empresa',
        ),

        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idempresa', models.BigAutoField(db_column='idempresa', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='empresaimagen/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.IntegerField()),
                ('publico', models.IntegerField()),
            ],
            options={
                'db_table': 'Empresa',
            },
        ),
    ]
