# Generated by Django 5.1.5 on 2025-02-05 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0003_remove_customuser_fechacreacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fechacreacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
