# Generated by Django 5.1.5 on 2025-05-04 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0004_alter_actividad_fechaentrega'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursodesafio',
            unique_together={('idproyecto', 'idcurso')},
        ),
        migrations.AddField(
            model_name='cursodesafio',
            name='idjurado1',
            field=models.ForeignKey(blank=True, db_column='idjurado1', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursodesafio_j1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursodesafio',
            name='idjurado2',
            field=models.ForeignKey(blank=True, db_column='idjurado2', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursodesafio_j2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cursodesafio',
            name='idjurado3',
            field=models.ForeignKey(blank=True, db_column='idjurado3', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cursodesafio_j3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cursodesafio',
            unique_together={('idjurado1', 'idjurado2', 'idjurado3'), ('idproyecto', 'idcurso')},
        ),
    ]
