# Generated by Django 5.1.5 on 2025-02-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0004_customuser_fechacreacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tabla', models.CharField(help_text='Nombre de la tabla a la que pertenece este estado', max_length=255)),
                ('identificador_tabla', models.CharField(help_text='Identificador único del registro dentro de la tabla', max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('clave', models.CharField(help_text='Clave del estado', max_length=255)),
                ('valor', models.CharField(help_text='Valor del estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['nombre_tabla', 'identificador_tabla'], name='gestioninve_nombre__3a106e_idx')],
                'unique_together': {('nombre_tabla', 'identificador_tabla', 'clave')},
            },
        ),
    ]
