# Generated by Django 5.1.5 on 2025-04-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0004_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionpropuesta',
            name='detallepropuesta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
