# Generated by Django 5.1.5 on 2025-04-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0005_alter_postulacionpropuesta_detallepropuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacionpropuesta',
            name='antecedentes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulacionpropuesta',
            name='cumplimientorequerimientos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postulacionpropuesta',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
