# Generated by Django 5.1.5 on 2025-02-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0005_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='archivosConvocatoriaDesafio/'),
        ),
        migrations.AlterField(
            model_name='archivoactividades',
            name='ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='archivosActividad/'),
        ),
        migrations.AlterField(
            model_name='archivopostulaciones',
            name='ubicacion',
            field=models.FileField(blank=True, null=True, upload_to='archivosPostulacion/'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='convocatoriaimagen/'),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='desafioimagen/'),
        ),
    ]
