# Generated by Django 5.1.5 on 2025-02-26 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0005_rename_activo_actividad_eliminado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubrica',
            name='idproyecto',
        ),
        migrations.AddField(
            model_name='curso',
            name='idrubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.rubrica'),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='actividadcronograma',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='archivoactividades',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='archivopostulaciones',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='curso',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='desafio',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='notificciones',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='postulante',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idcriterio', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('peso', models.FloatField()),
                ('puntaje', models.FloatField()),
                ('idrubrica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.rubrica')),
            ],
            options={
                'db_table': 'Criterio',
            },
        ),
    ]
