# Generated by Django 5.1.5 on 2025-04-10 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0006_alter_postulacionpropuesta_antecedentes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='idproyecto',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='idpostulacionpropuesta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.postulacionpropuesta'),
        ),
    ]
