# Generated by Django 5.1.5 on 2025-05-04 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0006_alter_cursodesafio_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cursodesafio',
            unique_together={('idjurado1', 'idjurado2', 'idjurado3'), ('idproyecto', 'idcurso')},
        ),
        migrations.AlterUniqueTogether(
            name='estado',
            unique_together={('nombre_tabla', 'identificador_tabla', 'clave')},
        ),
        migrations.AlterUniqueTogether(
            name='usercurso',
            unique_together={('iduser', 'idcurso', 'rol')},
        ),
        migrations.AlterUniqueTogether(
            name='usuariodesafio',
            unique_together={('iduser', 'idproyecto', 'rol')},
        ),
    ]
