# Generated by Django 5.1.5 on 2025-02-26 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0007_datostecnicos_remove_componente_idproyecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursodesafio',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='plantesis',
            name='idproyecto',
        ),
        migrations.AddField(
            model_name='cursodesafio',
            name='idplanformacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.plantesis'),
        ),
    ]
