# Generated by Django 5.1.5 on 2025-02-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0007_ubigeodepartamento_alter_actividad_titulo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ubigeoCiudad',
            new_name='ubigeoDistrito',
        ),
        migrations.AlterModelTable(
            name='ubigeodistrito',
            table='ubigeoDistrito',
        ),
    ]
