# Generated by Django 5.1.5 on 2025-05-05 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0007_alter_cursodesafio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='puntaje',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='pionero',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='practico',
        ),
        migrations.RemoveField(
            model_name='evaluacion',
            name='rentable',
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='idrubrica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.rubrica'),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='iduserevaluador',
            field=models.ForeignKey(db_column='iduserevaluador', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EvaluacionCriterio',
            fields=[
                ('eliminado', models.SmallIntegerField(default=0)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('puntaje', models.FloatField()),
                ('idcriterio', models.ForeignKey(db_column='idcriterio', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.criterio')),
                ('idevaluacion', models.ForeignKey(db_column='idevaluacion', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.evaluacion')),
            ],
            options={
                'db_table': 'evaluacion_criterio',
                'unique_together': {('idcriterio', 'idevaluacion')},
            },
        ),
    ]
