# Generated by Django 5.1.5 on 2025-02-18 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0008_rename_ubigeociudad_ubigeodistrito_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ubigeoPrivincia',
            new_name='ubigeoProvincia',
        ),
        migrations.AlterModelTable(
            name='ubigeoprovincia',
            table='ubigeoProvincia',
        ),
    ]
