# Generated by Django 5.1.5 on 2025-05-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0008_remove_criterio_puntaje_remove_evaluacion_pionero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncriterio',
            name='puntaje',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
