# Generated by Django 5.1.5 on 2025-02-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0009_alter_usercurso_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='estado',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
