# Generated by Django 5.1.5 on 2025-02-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0009_rename_ubigeoprivincia_ubigeoprovincia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeodepartamento',
            name='iddepartamento',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ubigeodistrito',
            name='idciudad',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ubigeoprovincia',
            name='idprovincia',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
