# Generated by Django 5.1.5 on 2025-05-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0009_alter_evaluacioncriterio_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncriterio',
            name='puntaje',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
