# Generated by Django 5.1.5 on 2025-02-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0010_postulacionpropuesta_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
