# Generated by Django 5.1.5 on 2025-05-05 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0010_alter_evaluacion_comentario_alter_evaluacion_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retroalimentacion',
            name='idusercreador',
            field=models.ForeignKey(db_column='idusercreador', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retroalimentacionacttecnica',
            name='idusercreador',
            field=models.ForeignKey(db_column='idusercreador', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
