# Generated by Django 5.1.5 on 2025-02-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0010_alter_ubigeodepartamento_iddepartamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gradoacademico',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
