# Generated by Django 5.1.5 on 2025-02-19 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0011_customuser_gradoacademico_customuser_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='cPostulacionPropuesta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('detallepropuesta', models.TextField()),
                ('titulo', models.TextField()),
                ('practico', models.FloatField(blank=True, null=True)),
                ('rentable', models.FloatField(blank=True, null=True)),
                ('pionero', models.FloatField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('practicocomentario', models.TextField(blank=True, null=True)),
                ('rentrablecomentario', models.TextField(blank=True, null=True)),
                ('pionerocomentario', models.TextField(blank=True, null=True)),
                ('antecedentes', models.TextField()),
                ('cumplimientorequerimientos', models.TextField()),
                ('idproyecto', models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
            ],
            options={
                'db_table': 'cpostulacion_propuesta',
            },
        ),
        migrations.CreateModel(
            name='cUserCurso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.SmallIntegerField()),
                ('idcurso', models.ForeignKey(db_column='idcurso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.curso')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cuser_curso',
                'unique_together': {('iduser', 'idcurso')},
            },
        ),
        migrations.CreateModel(
            name='cUsuarioDesafio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.SmallIntegerField()),
                ('idproyecto', models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cusuario_desafio',
                'unique_together': {('iduser', 'idproyecto')},
            },
        ),
    ]
