# Generated by Django 5.1.5 on 2025-03-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0011_customuser_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoria',
            name='grado',
            field=models.CharField(blank=True, choices=[('Pregrado', 'Pregrado'), ('Posgrado', 'Posgrado')], default='Otro', max_length=20, null=True),
        ),
    ]
