# Generated by Django 5.1.5 on 2025-05-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0011_retroalimentacion_idusercreador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursodesafio',
            name='iddatostecnicos',
        ),
        migrations.AddField(
            model_name='datostecnicos',
            name='idcursodesafio',
            field=models.ForeignKey(db_column='idcursodesafio', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.cursodesafio'),
            preserve_default=False,
        ),
    ]
