# Generated by Django 5.1.5 on 2025-02-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0012_cpostulacionpropuesta_cusercurso_cusuariodesafio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulacionpropuesta',
            table='apostulacion_propuesta',
        ),
        migrations.AlterModelTable(
            name='usercurso',
            table='auser_curso',
        ),
        migrations.AlterModelTable(
            name='usuariodesafio',
            table='ausuario_desafio',
        ),
    ]
