# Generated by Django 5.1.5 on 2025-03-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0012_alter_convocatoria_grado'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estado',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='plataforma',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
