# Generated by Django 5.1.5 on 2025-05-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0012_remove_cursodesafio_iddatostecnicos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='criterio',
            old_name='peso',
            new_name='puntaje',
        ),
        migrations.RemoveField(
            model_name='evaluacioncriterio',
            name='puntaje',
        ),
        migrations.AddField(
            model_name='rubrica',
            name='peso',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
