# Generated by Django 5.1.5 on 2025-05-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0013_rename_peso_criterio_puntaje_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='ReporteAnexo/'),
        ),
    ]
