# Generated by Django 5.1.5 on 2025-02-19 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0013_alter_postulacionpropuesta_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cpostulacionpropuesta',
            table='postulacion_propuesta',
        ),
        migrations.AlterModelTable(
            name='cusercurso',
            table='user_curso',
        ),
        migrations.AlterModelTable(
            name='cusuariodesafio',
            table='usuario_desafio',
        ),
    ]
