# Generated by Django 5.1.5 on 2025-03-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0013_customuser_estado_customuser_plataforma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='director',
        ),
    ]
