# Generated by Django 5.1.5 on 2025-02-19 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0014_alter_cpostulacionpropuesta_table_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cusercurso',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cusercurso',
            name='idcurso',
        ),
        migrations.RemoveField(
            model_name='cusercurso',
            name='iduser',
        ),
        migrations.AlterUniqueTogether(
            name='cusuariodesafio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cusuariodesafio',
            name='idproyecto',
        ),
        migrations.RemoveField(
            model_name='cusuariodesafio',
            name='iduser',
        ),
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercurso',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuariodesafio',
            name='id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacionpropuesta',
            name='idproyecto',
            field=models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio'),
        ),
        migrations.AlterField(
            model_name='usercurso',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariodesafio',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='postulacionpropuesta',
            table='postulacion_propuesta',
        ),
        migrations.AlterModelTable(
            name='usercurso',
            table='user_curso',
        ),
        migrations.AlterModelTable(
            name='usuariodesafio',
            table='usuario_desafio',
        ),
        migrations.DeleteModel(
            name='cPostulacionPropuesta',
        ),
        migrations.DeleteModel(
            name='cUserCurso',
        ),
        migrations.DeleteModel(
            name='cUsuarioDesafio',
        ),
    ]
