# Generated by Django 5.1.5 on 2025-05-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0014_alter_reporte_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='titulo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
