# Generated by Django 5.1.5 on 2025-02-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0015_alter_cusercurso_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convocatoria',
            name='idactividad',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='idconvocatoria',
        ),
        migrations.AddField(
            model_name='actividadcronograma',
            name='idconvocatoria',
            field=models.ForeignKey(blank=True, db_column='idconvocatoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.convocatoria'),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fechafin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='fechainicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convocatoria',
            name='grado',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
