# Generated by Django 5.1.5 on 2025-03-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0015_departamento_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='ubigeoPais',
            fields=[
                ('idpais', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ubigeoPais',
            },
        ),
    ]
