# Generated by Django 5.1.5 on 2025-05-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0015_componente_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubrica',
            name='nroorden',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rubrica',
            name='tipo',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
