# Generated by Django 5.1.5 on 2025-02-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0016_remove_convocatoria_idactividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gradoacademico',
            field=models.CharField(blank=True, choices=[('Secundaria', 'Secundaria'), ('Bachillerato', 'Bachillerato'), ('Universitario', 'Universitario'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado'), ('Otro', 'Otro')], default='Otro', max_length=20, null=True),
        ),
    ]
