# Generated by Django 5.1.5 on 2025-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0020_remove_curso_fecharegistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='tipodashboard',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
