# Generated by Django 5.1.5 on 2025-03-26 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0021_estado_tipodashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='iddepartamento',
            field=models.ForeignKey(blank=True, db_column='iddepartamento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.departamento'),
        ),
    ]
