# Generated by Django 5.1.5 on 2025-03-26 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0022_convocatoria_iddepartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='aceptado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='iduser',
            field=models.ForeignKey(db_column='iduser', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
