# Generated by Django 5.1.5 on 2025-03-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0024_rename_idproyecto_postulante_idpostulacionpropuesta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariorolsistema',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='usercurso',
            unique_together={('iduser', 'idcurso', 'rol')},
        ),
    ]
