# Generated by Django 5.1.5 on 2025-03-27 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0026_alter_usuariodesafio_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archivopostulaciones',
            old_name='idproyecto',
            new_name='idpostulacionpropuesta',
        ),
        migrations.RemoveField(
            model_name='archivopostulaciones',
            name='idconvocatoria',
        ),
    ]
