# Generated by Django 5.1.5 on 2025-03-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0027_rename_idproyecto_archivopostulaciones_idpostulacionpropuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='anexo1',
            field=models.FileField(blank=True, null=True, upload_to='PostulacionAnexo/'),
        ),
        migrations.AddField(
            model_name='postulacionpropuesta',
            name='anexo2',
            field=models.FileField(blank=True, null=True, upload_to='PostulacionAnexo/'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='PostulanteAnexo/'),
        ),
        migrations.AddField(
            model_name='postulante',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='postulante',
            name='dni',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ArchivoPostulaciones',
        ),
    ]
