# Generated by Django 5.1.5 on 2025-03-27 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0028_postulacionpropuesta_anexo1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='plataforma',
        ),
    ]
