# Generated by Django 5.1.5 on 2025-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0032_componente_eliminado_datostecnicos_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='evaluacion',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='plantesis',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
