# Generated by Django 5.1.5 on 2025-04-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0033_entregable_eliminado_evaluacion_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='reporte',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='retroalimentacion',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='retroalimentacionacttecnica',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rubrica',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
