# Generated by Django 5.1.5 on 2025-04-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0034_criterio_eliminado_presupuesto_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodesafio',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usercurso',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='usuariodesafio',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
