# Generated by Django 5.1.5 on 2025-04-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0035_cursodesafio_eliminado_usercurso_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariorolsistema',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
