# Generated by Django 5.1.5 on 2025-04-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0036_usuariorolsistema_eliminado'),
    ]

    operations = [
        migrations.RemoveField(
                    model_name='actividadtecnica',
                    name='eliminado' 
                ),
        migrations.AddField(
                    model_name='actividadtecnica',
                    name='eliminado',
                    field=models.BooleanField(default=0),
                ),
    ]
