# Generated by Django 5.1.5 on 2025-02-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0003_desafio_idconvocatoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_rol', models.IntegerField()),
                ('nombre_tabla', models.CharField(help_text='Nombre de la tabla a la que pertenece este estado', max_length=255)),
                ('identificador_tabla', models.CharField(help_text='Identificador único del registro dentro de la tabla', max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
    ]
