# Generated by Django 5.1.5 on 2025-02-25 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0004_rol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='actividadcronograma',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='actividadtecnica',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='archivo',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='archivoactividades',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='archivopostulaciones',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='convocatoria',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='desafio',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='notificciones',
            old_name='activo',
            new_name='eliminado',
        ),
        migrations.RenameField(
            model_name='postulante',
            old_name='activo',
            new_name='eliminado',
        ),
    ]
