# Generated by Django 5.1.5 on 2025-02-26 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0006_remove_rubrica_idproyecto_curso_idrubrica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTecnicos',
            fields=[
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('iddatostecnicos', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DatosTecnicos',
            },
        ),
        migrations.RemoveField(
            model_name='componente',
            name='idproyecto',
        ),
        migrations.RemoveField(
            model_name='desafio',
            name='idcurso',
        ),
        migrations.AddField(
            model_name='componente',
            name='iddatostecnicos',
            field=models.ForeignKey(blank=True, db_column='idproyecto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.datostecnicos'),
        ),
        migrations.CreateModel(
            name='CursoDesafio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.SmallIntegerField()),
                ('idcurso', models.ForeignKey(db_column='idcurso', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.curso')),
                ('idproyecto', models.ForeignKey(db_column='idproyecto', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.desafio')),
                ('iddatostecnicos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.datostecnicos')),
            ],
            options={
                'db_table': 'curso_desafio',
                'unique_together': {('idproyecto', 'idcurso')},
            },
        ),
    ]
