# Generated by Django 5.1.5 on 2025-02-27 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0008_remove_cursodesafio_rol_remove_plantesis_idproyecto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercurso',
            unique_together=set(),
        ),
    ]
