# Generated by Django 5.1.5 on 2025-03-13 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0014_remove_departamento_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='director',
            field=models.ForeignKey(db_column='iduser', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
