# Generated by Django 5.1.5 on 2025-03-20 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0016_ubigeopais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='identificador_tabla',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='nombre_tabla',
        ),
        migrations.CreateModel(
            name='UsuarioRolSistema',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('idrol', models.ForeignKey(db_column='idrol', on_delete=django.db.models.deletion.DO_NOTHING, to='gestioninvestigacionapp.rol')),
                ('iduser', models.ForeignKey(db_column='iduser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_rol',
                'unique_together': {('iduser', 'idrol')},
            },
        ),
    ]
