# Generated by Django 5.1.5 on 2025-03-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0017_remove_rol_identificador_tabla_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='id',
        ),
        migrations.AlterField(
            model_name='rol',
            name='identificador_rol',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
