# Generated by Django 5.1.5 on 2025-03-20 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0018_remove_rol_id_alter_rol_identificador_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='coordinador',
        ),
    ]
