# Generated by Django 5.1.5 on 2025-03-20 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0019_remove_curso_coordinador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='fecharegistro',
        ),
    ]
