# Generated by Django 5.1.5 on 2025-03-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0023_postulacionpropuesta_aceptado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulante',
            old_name='idproyecto',
            new_name='idpostulacionpropuesta',
        ),
    ]
