# Generated by Django 5.1.5 on 2025-03-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0025_alter_usuariorolsistema_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usuariodesafio',
            unique_together={('iduser', 'idproyecto', 'rol')},
        ),
    ]
