# Generated by Django 5.1.5 on 2025-04-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0030_customuser_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='rol',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ubigeodepartamento',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ubigeopais',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ubigeoprovincia',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
