# Generated by Django 5.1.5 on 2025-04-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioninvestigacionapp', '0031_estado_eliminado_rol_eliminado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='datostecnicos',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ubigeodistrito',
            name='eliminado',
            field=models.BooleanField(default=0),
        ),
    ]
